export const LOAD_TOAST_INFO = "LOAD_TOAST_INFO";
export const CLEAR_TOAST_INFO = "CLEAR_TOAST_INFO";
export const SELECT_DEVICE = "SELECT_DEVICE";
export const CLEAR_DEVICE = "CLEAR_DEVICE";

export const LOAD_DISPLAY_MESSAGE = "LOAD_DISPLAY_MESSAGE";
export const CLEAR_DISPLAY_MESSAGE = "CLEAR_DISPLAY_MESSAGE";

export const LOAD_SWIPE_DATA = "LOAD_SWIPE_DATA";
export const CLEAR_SWIPE_DATA = "CLEAR_SWIPE_DATA";