export const LOAD_TOAST_INFO = "LOAD_TOAST_INFO";
export const CLEAR_TOAST_INFO = "CLEAR_TOAST_INFO";
export const SELECT_DEVICE = "SELECT_DEVICE";
export const CLEAR_DEVICE = "CLEAR_DEVICE";

export const LOAD_DISPLAY_MESSAGE = "LOAD_DISPLAY_MESSAGE";
export const CLEAR_DISPLAY_MESSAGE = "CLEAR_DISPLAY_MESSAGE";

export const LOAD_SWIPE_DATA = "LOAD_SWIPE_DATA";
export const CLEAR_SWIPE_DATA = "CLEAR_SWIPE_DATA";

export const LOAD_EMV_DATA = "LOAD_EMV_DATA";
export const CLEAR_EMV_DATA = "CLEAR_EMV_DATA";

export const FLAG_CONNECTION_CHANGE = "FLAG_CONNECTION_CHANGE";

export const LOAD_PIN_DATA = "LOAD_PIN_DATA";
export const CLEAR_PIN_DATA = "CLEAR_PIN_DATA";
export const LOAD_TIP_DATA = "LOAD_TIP_DATA";
export const CLEAR_TIP_DATA = "CLEAR_TIP_DATA";